export enum HolidayType {
  CHRISTIAN,
  ETHIOPIAN_ORTHODOX,
  FIXED_DATE,
  FIXED_WEEKDAY,
  FIXED_WEEKDAY_BETWEEN_FIXED,
  FIXED_WEEKDAY_RELATIVE_TO_FIX,
  HEBREW,
  ISLAMIC,
  RELATIVE_TO_DATE,
  RELATIVE_TO_WEEKDAY
}

export type HolidayTypeKeyStrings = keyof typeof HolidayType;
