export enum ChristianHolidayType {
  ASCENSION_DAY,
  ASH_WEDNESDAY,
  CARNIVAL,
  CLEAN_MONDAY,
  CORPUS_CHRISTI,
  EASTER_MONDAY,
  EASTER_SATURDAY,
  EASTER_TUESDAY,
  EASTER,
  GENERAL_PRAYER_DAY,
  GOOD_FRIDAY,
  MARDI_GRAS,
  MAUNDY_THURSDAY,
  PENTECOST_MONDAY,
  PENTECOST,
  SACRED_HEART,
  SHROVE_MONDAY,
  WHIT_SUNDAY,
  WHIT_MONDAY
}

export type ChristianHolidayTypeKeyStrings = keyof typeof ChristianHolidayType;
