export enum HebrewHolidayType {
  ASARAH_BETEVET,
  ASERET_YEMEI_TESHUVA,
  HANUKKAH,
  LAG_BAOMER,
  ONE_ELUL,
  ONE_NISAN,
  PESACH,
  PURIM,
  ROSH_CODESH,
  ROSH_HASHANAH,
  SEFIRAH,
  SEVENTEEN_TAMMUZ,
  SHABBAT,
  SHAVOUT,
  SHEMINI_ATZERET,
  SUKKOT,
  TU_BISHVAT,
  TISHA_BAV,
  YOM_HAATZAMAUT,
  YOM_HASHOAH,
  YOM_HAZIKARON,
  YOM_KIPPUR,
  YOM_YERUSHALAIM
}

export type HebrewHolidayTypeKeyStrings = keyof typeof HebrewHolidayType;
